"""Convert scraped English WebVTT subtitles into a compact bundled JSON.

Input : ../http-proxy-lab/subtitles/<slug>/ep{NNN}_en.vtt
Map   : <slug> -> book_id via ../http-proxy-lab/<slug>-<bookid>-movie.html
Output: src/data/subtitles.json  =>  { bookId: { "<epNumber>": [[startCs, endCs, "text"], ...] } }

Times are stored as integer centiseconds to keep the file small.
Only movies present in src/data/episodes.json are included.
"""
import json
import os
import re
import glob
import sys

LANG = "en"
TS = re.compile(r"(\d{2}):(\d{2}):(\d{2})[.,](\d{3})")


def _to_cs(h, m, s, ms):
    return int(((int(h) * 3600 + int(m) * 60 + int(s)) * 1000 + int(ms)) / 10)


def parse_vtt(path):
    cues = []
    with open(path, encoding="utf-8-sig", errors="ignore") as f:
        raw = f.read()
    # Split into blocks on blank lines; a cue block contains a "-->" timing line.
    for block in re.split(r"\r?\n\r?\n", raw):
        lines = [ln for ln in block.splitlines() if ln.strip() != ""]
        if not lines:
            continue
        timing_idx = next((i for i, ln in enumerate(lines) if "-->" in ln), None)
        if timing_idx is None:
            continue
        stamps = TS.findall(lines[timing_idx])
        if len(stamps) < 2:
            continue
        start = _to_cs(*stamps[0])
        end = _to_cs(*stamps[1])
        text_lines = lines[timing_idx + 1:]
        text = " ".join(text_lines).strip()
        text = re.sub(r"<[^>]+>", "", text)  # strip any inline markup
        if text:
            cues.append([start, end, text])
    cues.sort(key=lambda c: c[0])
    return cues


def build(subs_dir, html_dir, episodes_path, out_path):
    # slug -> book_id from the movie HTML filenames.
    slug2id = {}
    for h in glob.glob(os.path.join(html_dir, "*-movie.html")):
        base = os.path.basename(h)[: -len("-movie.html")]
        m = re.match(r"(.+)-([0-9a-f]{24})$", base)
        if m:
            slug2id[m.group(1)] = m.group(2)

    catalog_ids = set(json.load(open(episodes_path, encoding="utf-8")).keys())

    out_dir = os.path.dirname(out_path)
    subs_out = os.path.join(out_dir, "subs")
    os.makedirs(subs_out, exist_ok=True)

    ids = []
    movies = 0
    total_eps = 0
    for slug in sorted(os.listdir(subs_dir)):
        folder = os.path.join(subs_dir, slug)
        if not os.path.isdir(folder):
            continue
        book_id = slug2id.get(slug)
        if not book_id or book_id not in catalog_ids:
            continue
        eps = {}
        for vtt in glob.glob(os.path.join(folder, f"ep*_{LANG}.vtt")):
            mnum = re.search(r"ep0*(\d+)_", os.path.basename(vtt))
            if not mnum:
                continue
            cues = parse_vtt(vtt)
            if cues:
                eps[str(int(mnum.group(1)))] = cues
        if eps:
            # One small asset file per movie -> downloaded on demand at runtime.
            with open(os.path.join(subs_out, f"{book_id}.bin"), "w", encoding="utf-8") as f:
                json.dump(eps, f, ensure_ascii=False, separators=(",", ":"))
            ids.append(book_id)
            movies += 1
            total_eps += len(eps)

    # Static require map (Metro needs literal requires). Maps bookId -> asset module.
    lines = ["// AUTO-GENERATED by scripts/build_subtitles.py — do not edit.", "export const SUBS_MODULES: Record<string, number> = {"]
    for bid in sorted(ids):
        lines.append(f'  "{bid}": require("./subs/{bid}.bin"),')
    lines.append("};")
    with open(os.path.join(out_dir, "subsMap.ts"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {movies} per-movie subtitle assets, {total_eps} episodes -> {subs_out} + subsMap.ts")
    return ids


if __name__ == "__main__":
    base = os.path.join("..", "http-proxy-lab")
    subs = sys.argv[1] if len(sys.argv) > 1 else os.path.join(base, "subtitles")
    # Output as .bin (JSON content) so Metro bundles it as a downloadable asset,
    # not a JS module — keeps the 21MB out of the JS bundle.
    build(subs, base, os.path.join("src", "data", "episodes.json"), os.path.join("src", "data", "subtitles.bin"))
