// AUTO-GENERATED by scripts/build_subtitles.py — do not edit.
export const SUBS_VI_MODULES: Record<string, number> = {
  "647ffff5be685964fe120217": require("./subs_vi/647ffff5be685964fe120217.bin"),
  "67ec430800e09545a501247d": require("./subs_vi/67ec430800e09545a501247d.bin"),
  "6825b313f981e578730e6174": require("./subs_vi/6825b313f981e578730e6174.bin"),
  "6836a4d1781ce526a9001446": require("./subs_vi/6836a4d1781ce526a9001446.bin"),
  "6968674a59095c2b4e0e5bd7": require("./subs_vi/6968674a59095c2b4e0e5bd7.bin"),
  "69b34991f0e1f3b6030b4974": require("./subs_vi/69b34991f0e1f3b6030b4974.bin"),
};
